name: Release client package

on:
  pull_request:
    paths:
      - "client-package/package.json"

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      working-directory: ./client-package

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check package version
        uses: technote-space/package-version-check-action@v1
        id: check
        with:
          COMMIT_DISABLED: 1
          PACKAGE_DIR: ${{env.working-directory}}
          PACKAGE_NAME: ${{env.working-directory}}/package.json
          GITHUB_TOKEN: ${{ secrets.GPR_TOKEN }}

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 10
          registry-url: 'https://npm.pkg.github.com'

      - name: Get yarn cache location
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
        working-directory: ${{env.working-directory}}

      - name: Restore yarn cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn --frozen-lockfile --ignore-engines --ignore-optional --non-interactive --silent --ignore-scripts --production=false
        working-directory: ${{env.working-directory}}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GPR_TOKEN }}

      - name: Release
        run: |
          npm config set '//npm.pkg.github.com/:_authToken' "${{ secrets.GITHUB_TOKEN }}"
          yarn release
        working-directory: ${{env.working-directory}}